export const FETCH_LOCATION_WEATHER_REQUEST = 'FETCH_LOCATION_WEATHER_REQUEST';
export const FETCH_LOCATION_WEATHER_SUCCESS = 'FETCH_LOCATION_WEATHER_SUCCESS';
export const FETCH_LOCATION_DATA_REQUEST = 'FETCH_LOCATION_DATA_REQUEST';
export const FETCH_LOCATION_DATA_SUCCESS = 'FETCH_LOCATION_DATA_SUCCESS';
export const FETCH_LOCATION_COORDS_SUCCESS = 'FETCH_LOCATION_COORDS_SUCCESS';
export const FETCH_LOCATION_COORDS_REQUEST = 'FETCH_LOCATION_COORDS_REQUEST';
export const FETCH_5_DAYS_FORECAST_REQUEST = 'FETCH_5_DAYS_FORECAST_REQUEST';
export const FETCH_5_DAYS_FORECAST_SUCCESS = 'FETCH_5_DAYS_FORECAST_SUCCESS';